spring.application.name=Upgrade

# Para definir el formato de despliegue de fecha/hora del log en la consola (HH en mayúscula para formato 24h)
logging.pattern.dateformat=HH:mm

# Para eliminar el arte ASCII de Spring al iniciar y limpiar la consola
spring.main.banner-mode=off

# Fundamental en desarrollo: desactiva el caché de Thymeleaf para ver los cambios html al recargar la página
spring.thymeleaf.cache=false

# ---------------------------------------------------------
# CONFIGURACIÓN TEMPORAL (SIN BASE DE DATOS)
# ---------------------------------------------------------
# Esto evita que Spring intente conectarse a MySQL al arrancar
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
