spring.application.name=Upgrade

# Para definir el formato de despliegue de fecha/hora del log en la consola (HH en mayúscula para formato 24h)
logging.pattern.dateformat=HH:mm

# Para eliminar el arte ASCII de Spring al iniciar y limpiar la consola
spring.main.banner-mode=off

# Fundamental en desarrollo: desactiva el caché de Thymeleaf para ver los cambios html al recargar la página
spring.thymeleaf.cache=false

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (MySQL)
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/upgrade_erp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=usuario_proyecto
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
# Muestra las consultas SQL en la consola 
spring.jpa.show-sql=true

# Formatea el SQL en la consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# 'update' mantiene el esquema de la BD sincronizado con tus entidades (clases Java)
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.port=8080